### ISSUE TITLE
U-Boot SPL 2020.07-rc3: DDR invalid size : 0x4, expected 0x20000000

### ISSUE THREAD

**Issue by FrankBau** [msloniewski/buildroot#1]
Hi Marcin,

yesterday, I cloned your buildroot repo, did a 
```
make odyssey_stm32mp157c_defconfig
make
```

Got errors in the dtb files, which I had to fix, see attached patch. [0001-dts-changes-to-fix-errors.zip](https://github.com/msloniewski/buildroot/files/5579144/0001-dts-changes-to-fix-errors.zip)

Now, my board is booting, but gets stuck in the SPL already:
```
U-Boot SPL 2020.07-rc3 (Nov 22 2020 - 07:26:37 +0100)
Model: Seeed Studio Odyssey-STM32MP157C Board
RAM: DDR3-DDR3L 16bits 533000Khz
DDR invalid size : 0x4, expected 0x20000000
DRAM init failed: -22
### ERROR ### Please RESET the board ###
```

No idea why I got those errors, didn't change anything. The seed stock image runs on the board. Do you have a clue?

**Comment by FrankBau** [comment]
moving on to U-Boot 2020.10 solved it, thx. Frank

**Comment by msloniewski** [comment]
Hi Frank!

I got busy recently, and put this project on back burner, but I'm planning to get back to it soon. Next Linux release (i.e. 5.10) will have mainline support for this board, I'm going to update buildroot support and post it on mailing list + I have some next patches to post for Linux and u-boot mailing lists 👍 

Cheers,
ms
